services:
  fiap.mctech.cart:
    container_name: mctech_cart
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      ALLOW_SWAGGER_UI: true
      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
      OPENID_AUDIENCE: ${OPENID_AUDIENCE}
    ports:
      - "8081:8081"
    networks:
      - local_network 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - local_network
networks:
  local_network:
    driver: bridge