apiVersion: v1
kind: Service
metadata:
  labels:
      app: mctech-cart-svc
  name: mctech-cart-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: mctech-cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
